#!/bin/bash

#
# Connect to iot device through ssh, fetching ip from registry.
#


# Check arguments
if [ $# -lt 1 ]; then
    echo "Usage: $(basename $0) <iot device name>"
    exit 1
fi

# Access fields
iot_name="$1"
iot_ip=$(retrieve-service-field "$iot_name" privateIp)
iot_port=$(retrieve-service-field "$iot_name" port)

if [ -z "$iot_ip" ]; then
    echo "Could not retrieve ip for $iot_name"
    exit 1
fi

# Connection
ssh -i ~/.ssh/"$iot_name"_id "$iot_name"@"$iot_ip" -p "$iot_port"
